language: cpp
    
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package hadley/testthat
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.9     
  - mkdir ~/.R
  - echo -e "CC=gcc-4.9 -std=gnu99\nCXX=g++-4.9 -std=c++14\nnCXX1X=g++-4.9\nCXXFLAGS=-g -O3\nCXX1XFLAGS=-g -O3\nCFLAGS=-g -O3\n" > ~/.R/Makevars
  
script:
  - R CMD INSTALL .
  - cd ..
  - git clone https://github.com/Rcpp11/Rcpp-test.git
  - mkdir tmp
  - touch tmp/DESCRIPTION
  - sed "s/Rcpp11/Rcpp14/" Rcpp-test/DESCRIPTION > tmp/DESCRIPTION
  - echo -e "SystemRequirements: C++14" >> tmp/DESCRIPTION
  - mv tmp/DESCRIPTION Rcpp-test/
  - git clone https://github.com/Rcpp11/attributes.git
  - R CMD INSTALL attributes
  - Rscript -e "library('attributes'); compileAttributes('Rcpp-test')"
  - R CMD INSTALL --install-tests Rcpp-test
  - Rscript -e "require(methods); require(RcppTest); require(testthat); require(devtools); test_package('RcppTest')"
  
notifications:
  email:
    on_success: change
    on_failure: change

